# Generated by Django 4.2.7 on 2025-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
