# Generated by Django 4.2.7 on 2025-06-04 07:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=200)),
                ('p_quantity', models.CharField(max_length=10)),
                ('p_prize', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=30, null=True)),
                ('datestart', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='files/')),
                ('date_statp', models.DateField(default=datetime.date(2025, 6, 4))),
            ],
        ),
    ]
