# Generated by Django 4.2.7 on 2025-09-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_number',
        ),
    ]
