# Generated by Django 4.2.7 on 2025-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0002_remove_book_book_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='sub_category',
            field=models.CharField(default='General', max_length=40),
        ),
    ]
