# Generated by Django 4.2.7 on 2025-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0002_add_category_order_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
    ]
