# Generated by Django 4.2.7 on 2025-09-10 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0003_rename_description_book_language_book_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
