# Generated by Django 4.2.7 on 2025-06-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0003_suggested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='date_statp',
        ),
    ]
