# Generated by Django 4.2.7 on 2025-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0004_remove_product_detail_date_statp'),
    ]

    operations = [
        migrations.CreateModel(
            name='issued_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_category', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
