# Generated by Django 4.2.7 on 2025-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0005_issued_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
