# Generated by Django 4.2.7 on 2025-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0007_alter_product_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('plan_choice', models.CharField(choices=[('general_1_year', 'General Membership - 1 Year'), ('general_6_months', 'General Membership - 6 Months'), ('general_3_months', 'General Membership - 3 Months'), ('special_daily_pass', 'Special Membership - Daily Pass'), ('special_1_month', 'Special Membership - 1 Month'), ('special_6_months', 'Special Membership - 6 Months'), ('special_1_year', 'Special Membership - 1 Year')], max_length=30)),
                ('aadhar_card_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
