# Generated by Django 5.2.4 on 2025-08-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0008_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.RemoveField(
            model_name='coustomer',
            name='password',
        ),
    ]
