# Generated by Django 4.2.7 on 2025-08-11 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0009_delete_membership_remove_coustomer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='coustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='coustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
