# Generated by Django 5.2.5 on 2025-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0010_coustomers_coustomer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coustomers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coustomers',
            name='name',
        ),
        migrations.AlterField(
            model_name='coustomers',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='coustomers',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
