# Generated by Django 5.2.4 on 2025-08-17 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0011_remove_coustomers_email_remove_coustomers_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_category', models.CharField(max_length=40)),
                ('book_description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='UserQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_secret', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_prize',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_quantity',
        ),
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book_prize',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='book_quantity',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggested',
            name='contact',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggested',
            name='email',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggested',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
