# Generated by Django 5.2.4 on 2025-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0012_book_detail_userqr_delete_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
