# Generated by Django 4.2.7 on 2025-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0013_alter_coustomer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqr',
            name='qr_image',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
    ]
