# Generated by Django 4.2.7 on 2025-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0014_userqr_qr_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coustomer',
            new_name='user',
        ),
    ]
