# Generated by Django 4.2.7 on 2025-08-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0015_rename_coustomer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='coustomer',
        ),
    ]
