# Generated by Django 4.2.7 on 2025-08-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0016_rename_user_coustomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coustomer',
            new_name='customer',
        ),
        migrations.RenameModel(
            old_name='coustomers',
            new_name='customers',
        ),
    ]
