# Generated by Django 4.2.7 on 2025-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0017_rename_coustomer_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
